version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: kyberswap-user-monitoring
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - MYSQL_ROOT_HOST=${DATABASE_HOST}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DBNAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database_mysql:
